defaults:
  - model: uvit_whisper_44k
  - _self_

# Training params
run_name: "my_run-hydra-nfdsnflksdjflkds"
batch_size: 2
max_steps: 1000
max_epochs: 1000
save_every: 100
eval_every: 1
num_workers: 0
require_features: true
pretrained_ckpt: null
tensorboard_logging: true
mlflow_logging: false

hydra:
  run:
    dir: "runs/${run_name}_${now:%Y-%m-%d_%H-%M-%S}"
  job:
    chdir: false
